version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8Gi
        reservations:
          cpus: '4'
          memory: 8Gi


  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    depends_on:
      - ollama
    ports:
      - 8080:8080
