version: '0.1'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    container_name: ollama
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - 'OLLAMA_API=http://ollama:11434/api'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G